In [1]:
import numpy as np
import os
import glob
import torch
from data_loaders.dataloader3d import get_dataloader, load_data, MotionDataset

In [26]:
def subtract_root(data):
    #only after frames have been cut
    root = (data[0,8,:]+data[0, 9, :])/2
    return data - root

In [ ]:
def normalize_height(data):
    head = (data[:, 2, :] + data[:, 5, :]) / 2
    root = (data[:, 8, :] + data[:, 9, :]) / 2
    height = np.linalg.norm(head - root, axis=1, keepdims=True)
    print(height.shape)
    return data[...,1]/(height[:,None,:]+1e-8)

In [2]:
def drop_duplicate_frames(data):
    """
    Drop frames where all 25 rows are identical.
    
    Parameters:
    -----------
    data : numpy.ndarray
        Array with shape (frames, 25, 5)
    
    Returns:
    --------
    numpy.ndarray
        Filtered array with duplicate frames removed
    """
    first_row = data[:, 0:1, :]  # Shape: (frames, 1, 5)
    all_rows_same = np.all(data == first_row, axis=(1,2))

    mask = ~all_rows_same
    return data[mask]

In [3]:
data=np.load("data_example/700/vitpose_c1_a4_2/vitpose/keypoints_3d/smpl-keypoints-3d_cut.npy")

In [20]:
data=drop_duplicate_frames(data)

In [23]:
data2=normalize_height(subtract_root(data))

(164, 1)


In [24]:
data2.shape

(164, 25, 5)

In [5]:
subtr=data[2,3,:]

In [6]:
subtr

array([ 0.   , -0.017,  0.   ,  1.   ,  0.   ])

In [12]:
data=data+subtr

In [13]:
data[0]

array([[ 0.   , -0.051,  0.   ,  3.   ,  0.   ],
       [ 0.   , -0.051,  0.   ,  3.   ,  0.   ],
       [ 0.   , -0.051,  0.   ,  3.   ,  0.   ],
       [ 0.   , -0.051,  0.   ,  3.   ,  0.   ],
       [ 0.   , -0.051,  0.   ,  3.   ,  0.   ],
       [ 0.   , -0.051,  0.   ,  3.   ,  0.   ],
       [ 0.   , -0.051,  0.   ,  3.   ,  0.   ],
       [ 0.   , -0.051,  0.   ,  3.   ,  0.   ],
       [ 0.   , -0.051,  0.   ,  3.   ,  0.   ],
       [ 0.   , -0.051,  0.   ,  3.   ,  0.   ],
       [ 0.   , -0.051,  0.   ,  3.   ,  0.   ],
       [ 0.   , -0.051,  0.   ,  3.   ,  0.   ],
       [ 0.   , -0.051,  0.   ,  3.   ,  0.   ],
       [ 0.   , -0.051,  0.   ,  3.   ,  0.   ],
       [ 0.   , -0.051,  0.   ,  3.   ,  0.   ],
       [ 0.   , -0.051,  0.   ,  3.   ,  0.   ],
       [ 0.   , -0.051,  0.   ,  3.   ,  0.   ],
       [ 0.   , -0.051,  0.   ,  3.   ,  0.   ],
       [ 0.   , -0.051,  0.   ,  3.   ,  0.   ],
       [ 0.   , -0.051,  0.   ,  3.   ,  0.   ],
       [ 0.   , -0.0

In [2]:
a,b = load_data("data_example", split='train')

In [8]:
dataset = MotionDataset(
    "gait",
    a,
    b,
    input_motion_length=200,
)

In [9]:
dataloader = get_dataloader(
    dataset, "train", batch_size=2, num_workers=2
)

In [10]:
print(len(dataset))        # number of samples
print(type(dataset))  

8
<class 'data_loaders.dataloader3d.MotionDataset'>


In [11]:
img, label = dataset[0]
print(img.shape, label.shape)  # shapes of the first sample

torch.Size([200, 75]) torch.Size([200, 75])


In [ ]:
img[122]

torch.Size([75])

In [14]:
i=0
print(a[i].shape)
print(b[i].shape)

torch.Size([122, 75])
torch.Size([48, 75])


In [ ]:
data=np.load("data_example/700/vitpose_c1_a4_2/vitpose/keypoints_3d/smpl-keypoints-3d_cut.npy")
data2=np.load("data_example/700/vitpose_c2_a4_2/vitpose/keypoints_3d/smpl-keypoints-3d_cut.npy")
data= drop_duplicate_frames(data)
data2= drop_duplicate_frames(data2)

In [17]:
print(data.shape, data2.shape)

(164, 25, 5) (144, 25, 5)


In [ ]:
for patient in os.listdir("data_example"):
    for file in sorted(os.listdir(os.path.join("data_example", patient))):
        take=file.split('_')
        if take[1]=='c1':
            #print(file)
            tup=take[0]+'_c2_'+"_".join(take[2:])
            #print('tuple:', tup)
            mypath=os.path.join("data_example", patient, file)
            mypath=os.path.join(mypath,"vitpose", "keypoints_3d", "smpl-keypoints-3d_cut.npy")
            print(mypath)
            data=np.load(mypath)
            print(np.load(mypath).shape)

    

In [36]:
data=np.load("data_example/753/vitpose_c1_a2_2/vitpose/keypoints_3d/smpl-keypoints-3d_cut.npy")

In [37]:
data.shape

(240, 25, 5)

In [38]:
data=np.delete(data, 1, axis=1)
data[100]

array([[-0.23823934,  1.0714808 , -0.38338893,  1.        ,  0.83414466],
       [-0.09489101,  1.02682005, -0.27751971,  1.        ,  0.82904044],
       [-0.01134131,  0.9267383 , -0.2228324 ,  1.        ,  0.88102578],
       [-0.05039085,  0.92870613, -0.32763197,  1.        ,  0.84406707],
       [-0.24162147,  1.02212285, -0.17851794,  1.        ,  0.82960045],
       [-0.20045324,  0.94049425, -0.06676494,  1.        ,  0.89366241],
       [-0.24709365,  0.87023268, -0.14836107,  1.        ,  0.82367277],
       [-0.20412006,  0.73600104, -0.19329517,  1.        ,  0.75605737],
       [-0.09916017,  0.72949511, -0.23106842,  1.        ,  0.75559718],
       [-0.10435282,  0.53666127, -0.18343513,  1.        ,  0.8927588 ],
       [-0.07538612,  0.34712743, -0.09905584,  1.        ,  0.83050084],
       [-0.20412006,  0.73600104, -0.19329517,  1.        ,  0.75605737],
       [-0.27130091,  0.58645559, -0.3199953 ,  1.        ,  0.90737803],
       [-0.26406693,  0.43389444, -0.1

In [ ]:
print(data.shape)

In [ ]:
tdata=data.reshape(-1,75)